### PR TITLE
Merge Hello CL sample and Ubuntu env setup docs

### PR DESCRIPTION
**Pull request by cqcallaw**

### CODE REVIEW

**Comment by cqcallaw** [comment]
Credit where it's due: the conditional use of git submodules is derived from https://foonathan.net/blog/2016/07/07/cmake-dependency-handling.html

**Comment by bashbaug** [comment]
Hi, thank you for your pull request, I really appreciate your contribution!  I think an example that actually does work with a kernel is a great addition to this "simple samples" repo.

I'd like to see a few small changes before accepting this PR though.  It might be easier to separate it into several PRs, actually:

1) I'd prefer not to make big changes to the CMakefile.  In particular, I'd like to keep explicitly using the Khronos headers and libs vs. the system headers and libs, and I'd like to keep the steps explicit and manual vs. being done with CMake magic.

2) Could you check that your sample builds and runs on Windows?  You may need to modify some parts of your sample to do this, such as reading the kernel from a relative path rather than an absolute path, or perhaps using a C++ raw string literal rather than a separate file.

I'll work on getting travis-ci and Appveyor setup for this repo if that'll help with (2).

Note that the upstream ICD loader has been updated and the build warnings should all be fixed now.

Thanks again!

**Comment by cqcallaw** [comment]
You're welcome; thanks for taking a look at this! 

Surveying the requested changes, I'm wondering if a cherry-pick might make sense here. The specified CMake changes looks like a series of revert patches, and Windows support isn't really a priority for me right now. Would it be simpler for you to pull in individual commits and tweak them however you'd like?

**Comment by bashbaug** [comment]
Simplified, rebased, and checked into master as 700c03681165b94b53290ab153c890e28e727b77.  Thanks!

**Pull request closed without merging**
