### PR TITLE
Ubuntu 19.04 and 19.10 environment setup instructions

### PR DESCRIPTION
**Pull request by cqcallaw**
Exactly duplicates 18.04 instructions as the procedures are identical

### CODE REVIEW

**Comment by bashbaug** [comment]
Thanks, this is great!  I'm fine accepting this PR as-is, but since the installation instructions are the same across all three files, have you considered some way to avoid duplication?  My only slight concern is keeping the three files in sync, if we fine bugs or make clarifications.

**Comment by cqcallaw** [comment]
Yeah, the duplication bothers me too. I originally tried to use symlinks instead, but found that Github didn't render them well. Merging all the instructions into a single document would work well until Ubuntu changes something; in my experience, this leads to inter-related headings and "refer to section H.4.1" jumps that are intimidating and difficult for novices to follow. Hyperlinking between document fragments helps but still breaks the mental flow. I don't know of any way to compose documents out of document fragments in Markdown (and I'm not sure the content warrants the maintenance effort of this approach anyway).

It's definitely a preference, but I'd rather shoulder an additional maintenance burden to make sure each document is as concise and readable as possible. Given the simplicity of the documents, I think this burden will be minor or non-existent, but please feel free to forward bug reports to me :)

**Comment by cqcallaw** [comment]
Another possibility is hyperlinks from the 19.04 and 19.10 docs to the 18.04 docs. It's not my first choice but would address the repetition concerns.

**Comment by bashbaug** [comment]
I'll merge this for now.  No reason to wait while we consider ways to address the duplication.  Thanks!

**Pull request merged**
